networks:
  sparkpg_network:

services:
  spark-master:
    image: my_first_spark
    build: .
    container_name: spark-master
    networks:
      - sparkpg_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-master.sh; tail -f /dev/null"
    ports:
      - '8080:8080'
      - '4040:4040'
    volumes:
      - spark-events:/opt/spark/events
      - ./input_files:/opt/data
      - ./jobs:/opt/jobs
      - ./logs:/opt/spark/logs

  spark-worker:
    image: my_first_spark
    build: .
    container_name: spark-worker1
    networks:
      - sparkpg_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-worker.sh  spark://spark-master:7077; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events
      - ./input_files:/opt/data
      - ./jobs:/opt/jobs
      - ./logs:/opt/spark/logs

  spark-history-server:
    image: my_first_spark
    build: .
    container_name: spark-history-server
    networks:
      - sparkpg_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-history-server.sh; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events
      - ./logs:/opt/spark/logs
    ports:
      - '18080:18080'

  mysql:
    image: mysql:latest
    container_name: mysql-db
    networks:
      - sparkpg_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: spark
      MYSQL_PASSWORD: spark123
    ports:
      - "3308:3306"
    volumes:
      - mysql_ecom:/var/lib/mysql

volumes:
  spark-events:
  mysql_ecom: